import { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-postgres'
import { sql } from 'drizzle-orm'

export async function up({ payload }: MigrateUpArgs): Promise<void> {
await payload.db.drizzle.execute(sql`

DO $$ BEGIN
 CREATE TYPE "enum_users_cej_from" AS ENUM('franceTravail', 'missionLocale');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DROP INDEX IF EXISTS "created_at_idx";
DROP INDEX IF EXISTS "email_idx";
DROP INDEX IF EXISTS "phone_number_idx";
DROP INDEX IF EXISTS "order_idx";
DROP INDEX IF EXISTS "parent_idx";
DROP INDEX IF EXISTS "path_idx";
DROP INDEX IF EXISTS "filename_idx";
DROP INDEX IF EXISTS "slug_idx";
DROP INDEX IF EXISTS "name_idx";
DROP INDEX IF EXISTS "_order_idx";
DROP INDEX IF EXISTS "_parent_id_idx";
DROP INDEX IF EXISTS "key_idx";
ALTER TABLE "users" ADD COLUMN "cejFrom" "enum_users_cej_from";
CREATE INDEX IF NOT EXISTS "admins_created_at_idx" ON "admins" ("created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "admins_email_idx" ON "admins" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "users_phone_number_idx" ON "users" ("phone_number");
CREATE INDEX IF NOT EXISTS "users_created_at_idx" ON "users" ("created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "users_email_idx" ON "users" ("email");
CREATE INDEX IF NOT EXISTS "users_rels_order_idx" ON "users_rels" ("order");
CREATE INDEX IF NOT EXISTS "users_rels_parent_idx" ON "users_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "users_rels_path_idx" ON "users_rels" ("path");
CREATE INDEX IF NOT EXISTS "supervisors_created_at_idx" ON "supervisors" ("created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "supervisors_email_idx" ON "supervisors" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "permissions_phone_number_idx" ON "permissions" ("phone_number");
CREATE INDEX IF NOT EXISTS "permissions_created_at_idx" ON "permissions" ("created_at");
CREATE INDEX IF NOT EXISTS "media_created_at_idx" ON "media" ("created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "media_filename_idx" ON "media" ("filename");
CREATE UNIQUE INDEX IF NOT EXISTS "categories_slug_idx" ON "categories" ("slug");
CREATE INDEX IF NOT EXISTS "categories_created_at_idx" ON "categories" ("created_at");
CREATE INDEX IF NOT EXISTS "categories_rels_order_idx" ON "categories_rels" ("order");
CREATE INDEX IF NOT EXISTS "categories_rels_parent_idx" ON "categories_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "categories_rels_path_idx" ON "categories_rels" ("path");
CREATE UNIQUE INDEX IF NOT EXISTS "partners_name_idx" ON "partners" ("name");
CREATE INDEX IF NOT EXISTS "partners_created_at_idx" ON "partners" ("created_at");
CREATE INDEX IF NOT EXISTS "partners_rels_order_idx" ON "partners_rels" ("order");
CREATE INDEX IF NOT EXISTS "partners_rels_parent_idx" ON "partners_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "partners_rels_path_idx" ON "partners_rels" ("path");
CREATE INDEX IF NOT EXISTS "offers_terms_of_use_order_idx" ON "offers_terms_of_use" ("_order");
CREATE INDEX IF NOT EXISTS "offers_terms_of_use_parent_id_idx" ON "offers_terms_of_use" ("_parent_id");
CREATE INDEX IF NOT EXISTS "offers_conditions_order_idx" ON "offers_conditions" ("_order");
CREATE INDEX IF NOT EXISTS "offers_conditions_parent_id_idx" ON "offers_conditions" ("_parent_id");
CREATE INDEX IF NOT EXISTS "offers_created_at_idx" ON "offers" ("created_at");
CREATE INDEX IF NOT EXISTS "offers_rels_order_idx" ON "offers_rels" ("order");
CREATE INDEX IF NOT EXISTS "offers_rels_parent_idx" ON "offers_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "offers_rels_path_idx" ON "offers_rels" ("path");
CREATE INDEX IF NOT EXISTS "coupons_created_at_idx" ON "coupons" ("created_at");
CREATE INDEX IF NOT EXISTS "coupons_rels_order_idx" ON "coupons_rels" ("order");
CREATE INDEX IF NOT EXISTS "coupons_rels_parent_idx" ON "coupons_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "coupons_rels_path_idx" ON "coupons_rels" ("path");
CREATE INDEX IF NOT EXISTS "savings_created_at_idx" ON "savings" ("created_at");
CREATE INDEX IF NOT EXISTS "savings_rels_order_idx" ON "savings_rels" ("order");
CREATE INDEX IF NOT EXISTS "savings_rels_parent_idx" ON "savings_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "savings_rels_path_idx" ON "savings_rels" ("path");
CREATE INDEX IF NOT EXISTS "payload_preferences_key_idx" ON "payload_preferences" ("key");
CREATE INDEX IF NOT EXISTS "payload_preferences_created_at_idx" ON "payload_preferences" ("created_at");
CREATE INDEX IF NOT EXISTS "payload_preferences_rels_order_idx" ON "payload_preferences_rels" ("order");
CREATE INDEX IF NOT EXISTS "payload_preferences_rels_parent_idx" ON "payload_preferences_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "payload_preferences_rels_path_idx" ON "payload_preferences_rels" ("path");
CREATE INDEX IF NOT EXISTS "payload_migrations_created_at_idx" ON "payload_migrations" ("created_at");
CREATE INDEX IF NOT EXISTS "quick_access_items_order_idx" ON "quick_access_items" ("_order");
CREATE INDEX IF NOT EXISTS "quick_access_items_parent_id_idx" ON "quick_access_items" ("_parent_id");
CREATE INDEX IF NOT EXISTS "quick_access_rels_order_idx" ON "quick_access_rels" ("order");
CREATE INDEX IF NOT EXISTS "quick_access_rels_parent_idx" ON "quick_access_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "quick_access_rels_path_idx" ON "quick_access_rels" ("path");
CREATE INDEX IF NOT EXISTS "landing_partners_items_order_idx" ON "landing_partners_items" ("_order");
CREATE INDEX IF NOT EXISTS "landing_partners_items_parent_id_idx" ON "landing_partners_items" ("_parent_id");
CREATE INDEX IF NOT EXISTS "landing_partners_rels_order_idx" ON "landing_partners_rels" ("order");
CREATE INDEX IF NOT EXISTS "landing_partners_rels_parent_idx" ON "landing_partners_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "landing_partners_rels_path_idx" ON "landing_partners_rels" ("path");
CREATE INDEX IF NOT EXISTS "landing_f_a_q_items_order_idx" ON "landing_f_a_q_items" ("_order");
CREATE INDEX IF NOT EXISTS "landing_f_a_q_items_parent_id_idx" ON "landing_f_a_q_items" ("_parent_id");`);

};

export async function down({ payload }: MigrateDownArgs): Promise<void> {
await payload.db.drizzle.execute(sql`

DROP INDEX IF EXISTS "admins_created_at_idx";
DROP INDEX IF EXISTS "admins_email_idx";
DROP INDEX IF EXISTS "users_phone_number_idx";
DROP INDEX IF EXISTS "users_created_at_idx";
DROP INDEX IF EXISTS "users_email_idx";
DROP INDEX IF EXISTS "users_rels_order_idx";
DROP INDEX IF EXISTS "users_rels_parent_idx";
DROP INDEX IF EXISTS "users_rels_path_idx";
DROP INDEX IF EXISTS "supervisors_created_at_idx";
DROP INDEX IF EXISTS "supervisors_email_idx";
DROP INDEX IF EXISTS "permissions_phone_number_idx";
DROP INDEX IF EXISTS "permissions_created_at_idx";
DROP INDEX IF EXISTS "media_created_at_idx";
DROP INDEX IF EXISTS "media_filename_idx";
DROP INDEX IF EXISTS "categories_slug_idx";
DROP INDEX IF EXISTS "categories_created_at_idx";
DROP INDEX IF EXISTS "categories_rels_order_idx";
DROP INDEX IF EXISTS "categories_rels_parent_idx";
DROP INDEX IF EXISTS "categories_rels_path_idx";
DROP INDEX IF EXISTS "partners_name_idx";
DROP INDEX IF EXISTS "partners_created_at_idx";
DROP INDEX IF EXISTS "partners_rels_order_idx";
DROP INDEX IF EXISTS "partners_rels_parent_idx";
DROP INDEX IF EXISTS "partners_rels_path_idx";
DROP INDEX IF EXISTS "offers_terms_of_use_order_idx";
DROP INDEX IF EXISTS "offers_terms_of_use_parent_id_idx";
DROP INDEX IF EXISTS "offers_conditions_order_idx";
DROP INDEX IF EXISTS "offers_conditions_parent_id_idx";
DROP INDEX IF EXISTS "offers_created_at_idx";
DROP INDEX IF EXISTS "offers_rels_order_idx";
DROP INDEX IF EXISTS "offers_rels_parent_idx";
DROP INDEX IF EXISTS "offers_rels_path_idx";
DROP INDEX IF EXISTS "coupons_created_at_idx";
DROP INDEX IF EXISTS "coupons_rels_order_idx";
DROP INDEX IF EXISTS "coupons_rels_parent_idx";
DROP INDEX IF EXISTS "coupons_rels_path_idx";
DROP INDEX IF EXISTS "savings_created_at_idx";
DROP INDEX IF EXISTS "savings_rels_order_idx";
DROP INDEX IF EXISTS "savings_rels_parent_idx";
DROP INDEX IF EXISTS "savings_rels_path_idx";
DROP INDEX IF EXISTS "payload_preferences_key_idx";
DROP INDEX IF EXISTS "payload_preferences_created_at_idx";
DROP INDEX IF EXISTS "payload_preferences_rels_order_idx";
DROP INDEX IF EXISTS "payload_preferences_rels_parent_idx";
DROP INDEX IF EXISTS "payload_preferences_rels_path_idx";
DROP INDEX IF EXISTS "payload_migrations_created_at_idx";
DROP INDEX IF EXISTS "quick_access_items_order_idx";
DROP INDEX IF EXISTS "quick_access_items_parent_id_idx";
DROP INDEX IF EXISTS "quick_access_rels_order_idx";
DROP INDEX IF EXISTS "quick_access_rels_parent_idx";
DROP INDEX IF EXISTS "quick_access_rels_path_idx";
DROP INDEX IF EXISTS "landing_partners_items_order_idx";
DROP INDEX IF EXISTS "landing_partners_items_parent_id_idx";
DROP INDEX IF EXISTS "landing_partners_rels_order_idx";
DROP INDEX IF EXISTS "landing_partners_rels_parent_idx";
DROP INDEX IF EXISTS "landing_partners_rels_path_idx";
DROP INDEX IF EXISTS "landing_f_a_q_items_order_idx";
DROP INDEX IF EXISTS "landing_f_a_q_items_parent_id_idx";
CREATE INDEX IF NOT EXISTS "created_at_idx" ON "admins" ("created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "email_idx" ON "admins" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "phone_number_idx" ON "users" ("phone_number");
CREATE INDEX IF NOT EXISTS "created_at_idx" ON "users" ("created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "email_idx" ON "users" ("email");
CREATE INDEX IF NOT EXISTS "order_idx" ON "users_rels" ("order");
CREATE INDEX IF NOT EXISTS "parent_idx" ON "users_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "path_idx" ON "users_rels" ("path");
CREATE INDEX IF NOT EXISTS "created_at_idx" ON "supervisors" ("created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "email_idx" ON "supervisors" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "phone_number_idx" ON "permissions" ("phone_number");
CREATE INDEX IF NOT EXISTS "created_at_idx" ON "permissions" ("created_at");
CREATE INDEX IF NOT EXISTS "created_at_idx" ON "media" ("created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "filename_idx" ON "media" ("filename");
CREATE UNIQUE INDEX IF NOT EXISTS "slug_idx" ON "categories" ("slug");
CREATE INDEX IF NOT EXISTS "created_at_idx" ON "categories" ("created_at");
CREATE INDEX IF NOT EXISTS "order_idx" ON "categories_rels" ("order");
CREATE INDEX IF NOT EXISTS "parent_idx" ON "categories_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "path_idx" ON "categories_rels" ("path");
CREATE UNIQUE INDEX IF NOT EXISTS "name_idx" ON "partners" ("name");
CREATE INDEX IF NOT EXISTS "created_at_idx" ON "partners" ("created_at");
CREATE INDEX IF NOT EXISTS "order_idx" ON "partners_rels" ("order");
CREATE INDEX IF NOT EXISTS "parent_idx" ON "partners_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "path_idx" ON "partners_rels" ("path");
CREATE INDEX IF NOT EXISTS "_order_idx" ON "offers_terms_of_use" ("_order");
CREATE INDEX IF NOT EXISTS "_parent_id_idx" ON "offers_terms_of_use" ("_parent_id");
CREATE INDEX IF NOT EXISTS "_order_idx" ON "offers_conditions" ("_order");
CREATE INDEX IF NOT EXISTS "_parent_id_idx" ON "offers_conditions" ("_parent_id");
CREATE INDEX IF NOT EXISTS "created_at_idx" ON "offers" ("created_at");
CREATE INDEX IF NOT EXISTS "order_idx" ON "offers_rels" ("order");
CREATE INDEX IF NOT EXISTS "parent_idx" ON "offers_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "path_idx" ON "offers_rels" ("path");
CREATE INDEX IF NOT EXISTS "created_at_idx" ON "coupons" ("created_at");
CREATE INDEX IF NOT EXISTS "order_idx" ON "coupons_rels" ("order");
CREATE INDEX IF NOT EXISTS "parent_idx" ON "coupons_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "path_idx" ON "coupons_rels" ("path");
CREATE INDEX IF NOT EXISTS "created_at_idx" ON "savings" ("created_at");
CREATE INDEX IF NOT EXISTS "order_idx" ON "savings_rels" ("order");
CREATE INDEX IF NOT EXISTS "parent_idx" ON "savings_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "path_idx" ON "savings_rels" ("path");
CREATE INDEX IF NOT EXISTS "key_idx" ON "payload_preferences" ("key");
CREATE INDEX IF NOT EXISTS "created_at_idx" ON "payload_preferences" ("created_at");
CREATE INDEX IF NOT EXISTS "order_idx" ON "payload_preferences_rels" ("order");
CREATE INDEX IF NOT EXISTS "parent_idx" ON "payload_preferences_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "path_idx" ON "payload_preferences_rels" ("path");
CREATE INDEX IF NOT EXISTS "created_at_idx" ON "payload_migrations" ("created_at");
CREATE INDEX IF NOT EXISTS "_order_idx" ON "quick_access_items" ("_order");
CREATE INDEX IF NOT EXISTS "_parent_id_idx" ON "quick_access_items" ("_parent_id");
CREATE INDEX IF NOT EXISTS "order_idx" ON "quick_access_rels" ("order");
CREATE INDEX IF NOT EXISTS "parent_idx" ON "quick_access_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "path_idx" ON "quick_access_rels" ("path");
CREATE INDEX IF NOT EXISTS "_order_idx" ON "landing_partners_items" ("_order");
CREATE INDEX IF NOT EXISTS "_parent_id_idx" ON "landing_partners_items" ("_parent_id");
CREATE INDEX IF NOT EXISTS "order_idx" ON "landing_partners_rels" ("order");
CREATE INDEX IF NOT EXISTS "parent_idx" ON "landing_partners_rels" ("parent_id");
CREATE INDEX IF NOT EXISTS "path_idx" ON "landing_partners_rels" ("path");
CREATE INDEX IF NOT EXISTS "_order_idx" ON "landing_f_a_q_items" ("_order");
CREATE INDEX IF NOT EXISTS "_parent_id_idx" ON "landing_f_a_q_items" ("_parent_id");
ALTER TABLE "users" DROP COLUMN IF EXISTS "cejFrom";`);

};
